-- SSAS Monitoring and Performance Queries
-- Production monitoring DMV queries

-- Active Sessions
SELECT
    SESSION_SPID AS SessionID,
    SESSION_USER_NAME AS UserName,
    SESSION_CURRENT_DATABASE AS Database,
    SESSION_ELAPSED_TIME_MS / 1000.0 AS ElapsedSeconds,
    SESSION_LAST_COMMAND AS LastCommand,
    SESSION_START_TIME AS StartTime,
    SESSION_STATUS AS Status
FROM $SYSTEM.DISCOVER_SESSIONS
WHERE SESSION_STATUS = 'Active'
ORDER BY SESSION_ELAPSED_TIME_MS DESC;

-- Long Running Queries
SELECT
    SESSION_SPID,
    SESSION_USER_NAME,
    SESSION_COMMAND_COUNT,
    SESSION_ELAPSED_TIME_MS / 1000.0 AS ElapsedSeconds,
    SESSION_LAST_COMMAND_START_TIME,
    SESSION_LAST_COMMAND_ELAPSED_TIME_MS / 1000.0 AS CommandElapsedSeconds
FROM $SYSTEM.DISCOVER_SESSIONS
WHERE SESSION_LAST_COMMAND_ELAPSED_TIME_MS > 30000
ORDER BY SESSION_LAST_COMMAND_ELAPSED_TIME_MS DESC;

-- Memory Usage
SELECT
    OBJECT_PARENT_PATH,
    OBJECT_ID,
    CAST(OBJECT_MEMORY_SHRINKABLE / 1024.0 / 1024 AS DECIMAL(10,2)) AS ShrinkableMB,
    CAST(OBJECT_MEMORY_NONSHRINKABLE / 1024.0 / 1024 AS DECIMAL(10,2)) AS NonShrinkableMB,
    CAST((OBJECT_MEMORY_SHRINKABLE + OBJECT_MEMORY_NONSHRINKABLE) / 1024.0 / 1024 AS DECIMAL(10,2)) AS TotalMB
FROM $SYSTEM.DISCOVER_OBJECT_MEMORY_USAGE
ORDER BY (OBJECT_MEMORY_SHRINKABLE + OBJECT_MEMORY_NONSHRINKABLE) DESC;

-- Aggregation Usage
SELECT
    PARTITION_NAME,
    AGGREGATION_NAME,
    USED_COUNT,
    ROWS,
    CAST(USED_SIZE / 1024.0 / 1024 AS DECIMAL(10,2)) AS SizeMB,
    CREATED_TIME,
    LAST_USED
FROM $SYSTEM.DISCOVER_PARTITION_STAT
WHERE AGGREGATION_NAME IS NOT NULL
ORDER BY USED_COUNT DESC;

-- Cache Hit Rate
SELECT
    CACHE_ID,
    CACHE_TYPE,
    CACHE_LOOKUPS,
    CACHE_HITS,
    CACHE_MISSES,
    CAST(CACHE_HITS * 100.0 / NULLIF(CACHE_LOOKUPS, 0) AS DECIMAL(5,2)) AS HitRatePercent,
    CAST(CACHE_SIZE / 1024.0 / 1024 AS DECIMAL(10,2)) AS CacheSizeMB
FROM $SYSTEM.DISCOVER_CACHES
ORDER BY CACHE_LOOKUPS DESC;

-- Processing Status
SELECT
    DATABASE_NAME,
    TABLE_NAME,
    PARTITION_NAME,
    STATE,
    LAST_PROCESSED,
    ROWS_COUNT,
    CAST(SIZE / 1024.0 / 1024 AS DECIMAL(10,2)) AS SizeMB
FROM $SYSTEM.TMSCHEMA_PARTITIONS
ORDER BY DATABASE_NAME, TABLE_NAME, PARTITION_NAME;

-- Connection Statistics
SELECT
    CONNECTION_ID,
    SESSION_SPID,
    CONNECTION_USER_NAME,
    CONNECTION_HOST_NAME,
    CONNECTION_HOST_APPLICATION,
    CONNECTION_START_TIME,
    CONNECTION_ELAPSED_TIME_MS / 1000.0 AS ElapsedSeconds,
    CONNECTION_LAST_COMMAND_START_TIME,
    CONNECTION_LAST_COMMAND_END_TIME
FROM $SYSTEM.DISCOVER_CONNECTIONS
ORDER BY CONNECTION_START_TIME DESC;
