-- Data Vault 2.0 DDL Implementation
-- Platform: Snowflake (adaptable to other platforms)
-- Description: Complete Data Vault 2.0 architecture with Hubs, Links, and Satellites

-- ============================================
-- DATABASE AND SCHEMA SETUP
-- ============================================

CREATE DATABASE IF NOT EXISTS DATA_VAULT;
USE DATABASE DATA_VAULT;

CREATE SCHEMA IF NOT EXISTS RAW_VAULT;
CREATE SCHEMA IF NOT EXISTS BUSINESS_VAULT;
CREATE SCHEMA IF NOT EXISTS INFORMATION_MART;

-- ============================================
-- HUB TABLES (Business Keys)
-- ============================================

-- Hub Customer: Unique customers
CREATE OR REPLACE TABLE RAW_VAULT.HUB_CUSTOMER (
    CUSTOMER_HK VARCHAR(32) PRIMARY KEY,  -- Hash key
    CUSTOMER_ID VARCHAR(50) NOT NULL,     -- Business key
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Hub table for Customer business entities';

-- Hub Product: Unique products
CREATE OR REPLACE TABLE RAW_VAULT.HUB_PRODUCT (
    PRODUCT_HK VARCHAR(32) PRIMARY KEY,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Hub table for Product business entities';

-- Hub Order: Unique orders
CREATE OR REPLACE TABLE RAW_VAULT.HUB_ORDER (
    ORDER_HK VARCHAR(32) PRIMARY KEY,
    ORDER_ID VARCHAR(50) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Hub table for Order business entities';

-- Hub Store: Unique stores
CREATE OR REPLACE TABLE RAW_VAULT.HUB_STORE (
    STORE_HK VARCHAR(32) PRIMARY KEY,
    STORE_ID VARCHAR(50) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Hub table for Store business entities';

-- Hub Supplier: Unique suppliers
CREATE OR REPLACE TABLE RAW_VAULT.HUB_SUPPLIER (
    SUPPLIER_HK VARCHAR(32) PRIMARY KEY,
    SUPPLIER_ID VARCHAR(50) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Hub table for Supplier business entities';

-- ============================================
-- LINK TABLES (Relationships)
-- ============================================

-- Link Order Line: Relationship between Order and Product
CREATE OR REPLACE TABLE RAW_VAULT.LINK_ORDER_LINE (
    ORDER_LINE_HK VARCHAR(32) PRIMARY KEY,
    ORDER_HK VARCHAR(32) NOT NULL,
    PRODUCT_HK VARCHAR(32) NOT NULL,
    -- Optional: Additional business keys for grain
    LINE_NUMBER INTEGER,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    -- Foreign keys
    CONSTRAINT FK_ORDER_LINE_ORDER FOREIGN KEY (ORDER_HK)
        REFERENCES RAW_VAULT.HUB_ORDER(ORDER_HK),
    CONSTRAINT FK_ORDER_LINE_PRODUCT FOREIGN KEY (PRODUCT_HK)
        REFERENCES RAW_VAULT.HUB_PRODUCT(PRODUCT_HK)
)
COMMENT = 'Link table connecting Orders to Products';

-- Link Customer Order: Relationship between Customer and Order
CREATE OR REPLACE TABLE RAW_VAULT.LINK_CUSTOMER_ORDER (
    CUSTOMER_ORDER_HK VARCHAR(32) PRIMARY KEY,
    CUSTOMER_HK VARCHAR(32) NOT NULL,
    ORDER_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_CUST_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_HK)
        REFERENCES RAW_VAULT.HUB_CUSTOMER(CUSTOMER_HK),
    CONSTRAINT FK_CUST_ORDER_ORDER FOREIGN KEY (ORDER_HK)
        REFERENCES RAW_VAULT.HUB_ORDER(ORDER_HK)
)
COMMENT = 'Link table connecting Customers to Orders';

-- Link Product Supplier: Many-to-Many relationship
CREATE OR REPLACE TABLE RAW_VAULT.LINK_PRODUCT_SUPPLIER (
    PRODUCT_SUPPLIER_HK VARCHAR(32) PRIMARY KEY,
    PRODUCT_HK VARCHAR(32) NOT NULL,
    SUPPLIER_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_PROD_SUPP_PRODUCT FOREIGN KEY (PRODUCT_HK)
        REFERENCES RAW_VAULT.HUB_PRODUCT(PRODUCT_HK),
    CONSTRAINT FK_PROD_SUPP_SUPPLIER FOREIGN KEY (SUPPLIER_HK)
        REFERENCES RAW_VAULT.HUB_SUPPLIER(SUPPLIER_HK)
)
COMMENT = 'Link table for Product-Supplier relationships';

-- Link Order Store: Order fulfillment location
CREATE OR REPLACE TABLE RAW_VAULT.LINK_ORDER_STORE (
    ORDER_STORE_HK VARCHAR(32) PRIMARY KEY,
    ORDER_HK VARCHAR(32) NOT NULL,
    STORE_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_ORDER_STORE_ORDER FOREIGN KEY (ORDER_HK)
        REFERENCES RAW_VAULT.HUB_ORDER(ORDER_HK),
    CONSTRAINT FK_ORDER_STORE_STORE FOREIGN KEY (STORE_HK)
        REFERENCES RAW_VAULT.HUB_STORE(STORE_HK)
)
COMMENT = 'Link table connecting Orders to Stores';

-- ============================================
-- SATELLITE TABLES (Descriptive Attributes)
-- ============================================

-- Satellite Customer: Customer descriptive data
CREATE OR REPLACE TABLE RAW_VAULT.SAT_CUSTOMER (
    CUSTOMER_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    LOAD_END_DATE TIMESTAMP_NTZ,
    -- Hash diff for change detection
    HASH_DIFF VARCHAR(32) NOT NULL,
    -- Descriptive attributes
    CUSTOMER_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    CUSTOMER_SEGMENT VARCHAR(50),
    CUSTOMER_TIER VARCHAR(20),
    COUNTRY VARCHAR(100),
    STATE VARCHAR(100),
    CITY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    -- Metadata
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    -- Primary key
    PRIMARY KEY (CUSTOMER_HK, LOAD_DATE),
    -- Foreign key
    CONSTRAINT FK_SAT_CUSTOMER_HUB FOREIGN KEY (CUSTOMER_HK)
        REFERENCES RAW_VAULT.HUB_CUSTOMER(CUSTOMER_HK)
)
COMMENT = 'Satellite with Customer descriptive attributes';

-- Satellite Product: Product descriptive data
CREATE OR REPLACE TABLE RAW_VAULT.SAT_PRODUCT (
    PRODUCT_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    LOAD_END_DATE TIMESTAMP_NTZ,
    HASH_DIFF VARCHAR(32) NOT NULL,
    -- Descriptive attributes
    PRODUCT_NAME VARCHAR(200),
    PRODUCT_DESCRIPTION VARCHAR(1000),
    SKU VARCHAR(100),
    BRAND VARCHAR(100),
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    UNIT_COST DECIMAL(12, 2),
    UNIT_PRICE DECIMAL(12, 2),
    IS_ACTIVE BOOLEAN,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PRODUCT_HK, LOAD_DATE),
    CONSTRAINT FK_SAT_PRODUCT_HUB FOREIGN KEY (PRODUCT_HK)
        REFERENCES RAW_VAULT.HUB_PRODUCT(PRODUCT_HK)
)
COMMENT = 'Satellite with Product descriptive attributes';

-- Satellite Order: Order header information
CREATE OR REPLACE TABLE RAW_VAULT.SAT_ORDER (
    ORDER_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    LOAD_END_DATE TIMESTAMP_NTZ,
    HASH_DIFF VARCHAR(32) NOT NULL,
    -- Descriptive attributes
    ORDER_NUMBER VARCHAR(100),
    ORDER_STATUS VARCHAR(50),
    ORDER_DATE DATE,
    PAYMENT_METHOD VARCHAR(50),
    SHIPPING_METHOD VARCHAR(50),
    SUBTOTAL_AMOUNT DECIMAL(12, 2),
    DISCOUNT_AMOUNT DECIMAL(12, 2),
    TAX_AMOUNT DECIMAL(12, 2),
    SHIPPING_AMOUNT DECIMAL(12, 2),
    TOTAL_AMOUNT DECIMAL(12, 2),
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ORDER_HK, LOAD_DATE),
    CONSTRAINT FK_SAT_ORDER_HUB FOREIGN KEY (ORDER_HK)
        REFERENCES RAW_VAULT.HUB_ORDER(ORDER_HK)
)
COMMENT = 'Satellite with Order header attributes';

-- Satellite Order Line: Line item measures
CREATE OR REPLACE TABLE RAW_VAULT.SAT_ORDER_LINE (
    ORDER_LINE_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    LOAD_END_DATE TIMESTAMP_NTZ,
    HASH_DIFF VARCHAR(32) NOT NULL,
    -- Transactional attributes
    QUANTITY INTEGER,
    UNIT_PRICE DECIMAL(12, 2),
    DISCOUNT_PERCENTAGE DECIMAL(5, 2),
    DISCOUNT_AMOUNT DECIMAL(12, 2),
    LINE_TOTAL DECIMAL(12, 2),
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ORDER_LINE_HK, LOAD_DATE),
    CONSTRAINT FK_SAT_ORDER_LINE_LINK FOREIGN KEY (ORDER_LINE_HK)
        REFERENCES RAW_VAULT.LINK_ORDER_LINE(ORDER_LINE_HK)
)
COMMENT = 'Satellite with Order Line transaction details';

-- Satellite Store: Store descriptive data
CREATE OR REPLACE TABLE RAW_VAULT.SAT_STORE (
    STORE_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    LOAD_END_DATE TIMESTAMP_NTZ,
    HASH_DIFF VARCHAR(32) NOT NULL,
    -- Descriptive attributes
    STORE_NAME VARCHAR(200),
    STORE_TYPE VARCHAR(50),
    STORE_SIZE_SQ_FT INTEGER,
    COUNTRY VARCHAR(100),
    STATE VARCHAR(100),
    CITY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    REGION VARCHAR(100),
    DISTRICT VARCHAR(100),
    MANAGER_NAME VARCHAR(200),
    OPENING_DATE DATE,
    IS_ACTIVE BOOLEAN,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (STORE_HK, LOAD_DATE),
    CONSTRAINT FK_SAT_STORE_HUB FOREIGN KEY (STORE_HK)
        REFERENCES RAW_VAULT.HUB_STORE(STORE_HK)
)
COMMENT = 'Satellite with Store descriptive attributes';

-- Multi-source satellite example: Customer from multiple systems
CREATE OR REPLACE TABLE RAW_VAULT.SAT_CUSTOMER_CRM (
    CUSTOMER_HK VARCHAR(32) NOT NULL,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    LOAD_END_DATE TIMESTAMP_NTZ,
    HASH_DIFF VARCHAR(32) NOT NULL,
    -- CRM-specific attributes
    LOYALTY_POINTS INTEGER,
    LIFETIME_VALUE DECIMAL(12, 2),
    PREFERRED_CONTACT_METHOD VARCHAR(50),
    MARKETING_OPT_IN BOOLEAN,
    LAST_CONTACT_DATE DATE,
    RECORD_SOURCE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_HK, LOAD_DATE),
    CONSTRAINT FK_SAT_CUSTOMER_CRM_HUB FOREIGN KEY (CUSTOMER_HK)
        REFERENCES RAW_VAULT.HUB_CUSTOMER(CUSTOMER_HK)
)
COMMENT = 'Satellite with Customer CRM-specific attributes';

-- ============================================
-- REFERENCE TABLES (Static/Slowly Changing)
-- ============================================

-- Reference data for codes and lookups
CREATE OR REPLACE TABLE RAW_VAULT.REF_ORDER_STATUS (
    STATUS_CODE VARCHAR(50) PRIMARY KEY,
    STATUS_NAME VARCHAR(100),
    STATUS_DESCRIPTION VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    RECORD_SOURCE VARCHAR(50) NOT NULL
)
COMMENT = 'Reference table for Order Status codes';

-- ============================================
-- POINT-IN-TIME (PIT) TABLES
-- ============================================

-- PIT table for Customer: Snapshot at specific points in time
CREATE OR REPLACE TABLE BUSINESS_VAULT.PIT_CUSTOMER (
    CUSTOMER_HK VARCHAR(32) NOT NULL,
    SNAPSHOT_DATE DATE NOT NULL,
    -- Satellite load dates (point-in-time)
    SAT_CUSTOMER_LOAD_DATE TIMESTAMP_NTZ,
    SAT_CUSTOMER_CRM_LOAD_DATE TIMESTAMP_NTZ,
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_HK, SNAPSHOT_DATE)
)
COMMENT = 'Point-in-time table for Customer satellites';

-- ============================================
-- BRIDGE TABLES
-- ============================================

-- Bridge table to connect multiple entities efficiently
CREATE OR REPLACE TABLE BUSINESS_VAULT.BRIDGE_ORDER_DETAILS (
    ORDER_HK VARCHAR(32) NOT NULL,
    CUSTOMER_HK VARCHAR(32),
    STORE_HK VARCHAR(32),
    ORDER_LINE_HK VARCHAR(32),
    PRODUCT_HK VARCHAR(32),
    LOAD_DATE TIMESTAMP_NTZ NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Bridge table combining order-related entities';

-- ============================================
-- HASH KEY GENERATION EXAMPLES
-- ============================================

-- Example: Generating hash keys for loading
/*
-- Hub Customer load
INSERT INTO RAW_VAULT.HUB_CUSTOMER (
    CUSTOMER_HK,
    CUSTOMER_ID,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(UPPER(TRIM(customer_id))) AS CUSTOMER_HK,
    customer_id AS CUSTOMER_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    'SOURCE_SYSTEM_1' AS RECORD_SOURCE
FROM staging.customers src
WHERE NOT EXISTS (
    SELECT 1
    FROM RAW_VAULT.HUB_CUSTOMER hub
    WHERE hub.CUSTOMER_HK = MD5(UPPER(TRIM(src.customer_id)))
);

-- Link Customer Order load
INSERT INTO RAW_VAULT.LINK_CUSTOMER_ORDER (
    CUSTOMER_ORDER_HK,
    CUSTOMER_HK,
    ORDER_HK,
    LOAD_DATE,
    RECORD_SOURCE
)
SELECT
    MD5(CONCAT(
        MD5(UPPER(TRIM(customer_id))),
        MD5(UPPER(TRIM(order_id)))
    )) AS CUSTOMER_ORDER_HK,
    MD5(UPPER(TRIM(customer_id))) AS CUSTOMER_HK,
    MD5(UPPER(TRIM(order_id))) AS ORDER_HK,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    'SOURCE_SYSTEM_1' AS RECORD_SOURCE
FROM staging.orders src
WHERE NOT EXISTS (
    SELECT 1
    FROM RAW_VAULT.LINK_CUSTOMER_ORDER lnk
    WHERE lnk.CUSTOMER_ORDER_HK = MD5(CONCAT(
        MD5(UPPER(TRIM(src.customer_id))),
        MD5(UPPER(TRIM(src.order_id)))
    ))
);

-- Satellite Customer load with hash diff
INSERT INTO RAW_VAULT.SAT_CUSTOMER (
    CUSTOMER_HK,
    LOAD_DATE,
    HASH_DIFF,
    CUSTOMER_NAME,
    EMAIL,
    PHONE,
    CUSTOMER_SEGMENT,
    RECORD_SOURCE
)
SELECT
    MD5(UPPER(TRIM(customer_id))) AS CUSTOMER_HK,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    MD5(CONCAT(
        COALESCE(customer_name, ''), '|',
        COALESCE(email, ''), '|',
        COALESCE(phone, ''), '|',
        COALESCE(segment, '')
    )) AS HASH_DIFF,
    customer_name,
    email,
    phone,
    segment AS CUSTOMER_SEGMENT,
    'SOURCE_SYSTEM_1' AS RECORD_SOURCE
FROM staging.customers src
WHERE MD5(CONCAT(
    COALESCE(customer_name, ''), '|',
    COALESCE(email, ''), '|',
    COALESCE(phone, ''), '|',
    COALESCE(segment, '')
)) NOT IN (
    -- Only load if hash diff changed
    SELECT HASH_DIFF
    FROM RAW_VAULT.SAT_CUSTOMER sat
    WHERE sat.CUSTOMER_HK = MD5(UPPER(TRIM(src.customer_id)))
      AND sat.LOAD_END_DATE IS NULL
);
*/

-- ============================================
-- INFORMATION MART VIEWS
-- ============================================

-- Denormalized view for reporting: Customer Orders
CREATE OR REPLACE VIEW INFORMATION_MART.VW_CUSTOMER_ORDERS AS
SELECT
    hc.CUSTOMER_ID,
    sc.CUSTOMER_NAME,
    sc.EMAIL,
    sc.CUSTOMER_SEGMENT,
    ho.ORDER_ID,
    so.ORDER_NUMBER,
    so.ORDER_DATE,
    so.ORDER_STATUS,
    so.TOTAL_AMOUNT
FROM RAW_VAULT.HUB_CUSTOMER hc
JOIN RAW_VAULT.SAT_CUSTOMER sc
    ON hc.CUSTOMER_HK = sc.CUSTOMER_HK
    AND sc.LOAD_END_DATE IS NULL  -- Current record
JOIN RAW_VAULT.LINK_CUSTOMER_ORDER lco
    ON hc.CUSTOMER_HK = lco.CUSTOMER_HK
JOIN RAW_VAULT.HUB_ORDER ho
    ON lco.ORDER_HK = ho.ORDER_HK
JOIN RAW_VAULT.SAT_ORDER so
    ON ho.ORDER_HK = so.ORDER_HK
    AND so.LOAD_END_DATE IS NULL;

-- Historical analysis view: Customer changes over time
CREATE OR REPLACE VIEW INFORMATION_MART.VW_CUSTOMER_HISTORY AS
SELECT
    hc.CUSTOMER_ID,
    sc.CUSTOMER_NAME,
    sc.EMAIL,
    sc.CUSTOMER_SEGMENT,
    sc.CUSTOMER_TIER,
    sc.LOAD_DATE AS EFFECTIVE_FROM,
    COALESCE(sc.LOAD_END_DATE, '9999-12-31'::TIMESTAMP) AS EFFECTIVE_TO,
    CASE WHEN sc.LOAD_END_DATE IS NULL THEN TRUE ELSE FALSE END AS IS_CURRENT
FROM RAW_VAULT.HUB_CUSTOMER hc
JOIN RAW_VAULT.SAT_CUSTOMER sc
    ON hc.CUSTOMER_HK = sc.CUSTOMER_HK
ORDER BY hc.CUSTOMER_ID, sc.LOAD_DATE DESC;

-- ============================================
-- COMMENTS
-- ============================================

COMMENT ON SCHEMA RAW_VAULT IS 'Raw Data Vault: Hubs, Links, and Satellites';
COMMENT ON SCHEMA BUSINESS_VAULT IS 'Business Vault: PITs, Bridges, and computed attributes';
COMMENT ON SCHEMA INFORMATION_MART IS 'Information Marts: Dimensional models for reporting';
