-- Snowflake Star Schema DDL
-- Retail Sales Data Warehouse
-- Platform: Snowflake
-- Description: Complete star schema implementation with optimizations

-- Database and Schema Setup
CREATE DATABASE IF NOT EXISTS RETAIL_DW;
USE DATABASE RETAIL_DW;

CREATE SCHEMA IF NOT EXISTS DIM;
CREATE SCHEMA IF NOT EXISTS FACT;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- ============================================
-- DIMENSION TABLES
-- ============================================

-- Date Dimension
CREATE OR REPLACE TABLE DIM.DIM_DATE (
    DATE_KEY INTEGER PRIMARY KEY,
    DATE_VALUE DATE NOT NULL,
    DAY_OF_WEEK INTEGER,
    DAY_NAME VARCHAR(10),
    DAY_OF_MONTH INTEGER,
    DAY_OF_YEAR INTEGER,
    WEEK_OF_YEAR INTEGER,
    MONTH_NUMBER INTEGER,
    MONTH_NAME VARCHAR(10),
    QUARTER INTEGER,
    QUARTER_NAME VARCHAR(2),
    YEAR INTEGER,
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN,
    HOLIDAY_NAME VARCHAR(100),
    FISCAL_YEAR INTEGER,
    FISCAL_QUARTER INTEGER,
    FISCAL_MONTH INTEGER,
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (DATE_VALUE)
COMMENT = 'Date dimension with calendar and fiscal attributes';

-- Customer Dimension (SCD Type 2)
CREATE OR REPLACE TABLE DIM.DIM_CUSTOMER (
    CUSTOMER_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    CUSTOMER_NAME VARCHAR(200),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(50),
    CUSTOMER_SEGMENT VARCHAR(50),
    CUSTOMER_TIER VARCHAR(20),
    COUNTRY VARCHAR(100),
    STATE VARCHAR(100),
    CITY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    -- SCD Type 2 columns
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CUSTOMER_ID, IS_CURRENT)
COMMENT = 'Customer dimension with SCD Type 2 tracking';

-- Product Dimension (SCD Type 2)
CREATE OR REPLACE TABLE DIM.DIM_PRODUCT (
    PRODUCT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(200),
    PRODUCT_DESCRIPTION VARCHAR(1000),
    SKU VARCHAR(100),
    BRAND VARCHAR(100),
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    UNIT_COST DECIMAL(12, 2),
    UNIT_PRICE DECIMAL(12, 2),
    IS_ACTIVE BOOLEAN,
    -- SCD Type 2 columns
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    -- Metadata
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (PRODUCT_ID, IS_CURRENT)
COMMENT = 'Product dimension with SCD Type 2 tracking';

-- Store Dimension
CREATE OR REPLACE TABLE DIM.DIM_STORE (
    STORE_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    STORE_ID VARCHAR(50) NOT NULL UNIQUE,
    STORE_NAME VARCHAR(200),
    STORE_TYPE VARCHAR(50),
    STORE_SIZE_SQ_FT INTEGER,
    COUNTRY VARCHAR(100),
    STATE VARCHAR(100),
    CITY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    REGION VARCHAR(100),
    DISTRICT VARCHAR(100),
    MANAGER_NAME VARCHAR(200),
    OPENING_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (STORE_ID)
COMMENT = 'Store location dimension';

-- Employee Dimension
CREATE OR REPLACE TABLE DIM.DIM_EMPLOYEE (
    EMPLOYEE_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(50) NOT NULL,
    EMPLOYEE_NAME VARCHAR(200),
    JOB_TITLE VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    MANAGER_ID VARCHAR(50),
    HIRE_DATE DATE,
    -- SCD Type 2 columns
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (EMPLOYEE_ID, IS_CURRENT)
COMMENT = 'Employee dimension with SCD Type 2 tracking';

-- Promotion Dimension
CREATE OR REPLACE TABLE DIM.DIM_PROMOTION (
    PROMOTION_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PROMOTION_ID VARCHAR(50) NOT NULL UNIQUE,
    PROMOTION_NAME VARCHAR(200),
    PROMOTION_TYPE VARCHAR(50),
    DISCOUNT_PERCENTAGE DECIMAL(5, 2),
    DISCOUNT_AMOUNT DECIMAL(12, 2),
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Promotion dimension';

-- ============================================
-- FACT TABLES
-- ============================================

-- Sales Fact (Transaction grain)
CREATE OR REPLACE TABLE FACT.FACT_SALES (
    SALES_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    -- Foreign Keys
    DATE_KEY INTEGER NOT NULL,
    CUSTOMER_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER NOT NULL,
    EMPLOYEE_KEY INTEGER,
    PROMOTION_KEY INTEGER,
    -- Degenerate Dimensions
    TRANSACTION_ID VARCHAR(100) NOT NULL,
    LINE_ITEM_NUMBER INTEGER,
    -- Measures
    QUANTITY INTEGER,
    UNIT_PRICE DECIMAL(12, 2),
    UNIT_COST DECIMAL(12, 2),
    GROSS_SALES_AMOUNT DECIMAL(12, 2),
    DISCOUNT_AMOUNT DECIMAL(12, 2),
    NET_SALES_AMOUNT DECIMAL(12, 2),
    TAX_AMOUNT DECIMAL(12, 2),
    TOTAL_AMOUNT DECIMAL(12, 2),
    PROFIT_AMOUNT DECIMAL(12, 2),
    -- Metadata
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_SYSTEM VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    -- Foreign Key Constraints
    CONSTRAINT FK_SALES_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM.DIM_DATE(DATE_KEY),
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM.DIM_CUSTOMER(CUSTOMER_KEY),
    CONSTRAINT FK_SALES_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM.DIM_PRODUCT(PRODUCT_KEY),
    CONSTRAINT FK_SALES_STORE FOREIGN KEY (STORE_KEY) REFERENCES DIM.DIM_STORE(STORE_KEY)
)
CLUSTER BY (DATE_KEY, STORE_KEY)
COMMENT = 'Sales transactions fact table at line item grain';

-- Inventory Snapshot Fact (Periodic Snapshot)
CREATE OR REPLACE TABLE FACT.FACT_INVENTORY_SNAPSHOT (
    INVENTORY_SNAPSHOT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    -- Foreign Keys
    DATE_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER NOT NULL,
    -- Measures
    BEGINNING_INVENTORY INTEGER,
    UNITS_RECEIVED INTEGER,
    UNITS_SOLD INTEGER,
    UNITS_RETURNED INTEGER,
    UNITS_ADJUSTED INTEGER,
    ENDING_INVENTORY INTEGER,
    INVENTORY_VALUE DECIMAL(12, 2),
    DAYS_OF_SUPPLY INTEGER,
    REORDER_POINT INTEGER,
    IS_OUT_OF_STOCK BOOLEAN,
    -- Metadata
    SNAPSHOT_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    -- Foreign Key Constraints
    CONSTRAINT FK_INV_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM.DIM_DATE(DATE_KEY),
    CONSTRAINT FK_INV_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM.DIM_PRODUCT(PRODUCT_KEY),
    CONSTRAINT FK_INV_STORE FOREIGN KEY (STORE_KEY) REFERENCES DIM.DIM_STORE(STORE_KEY)
)
CLUSTER BY (DATE_KEY, STORE_KEY)
COMMENT = 'Daily inventory snapshot fact table';

-- Order Fulfillment Fact (Accumulating Snapshot)
CREATE OR REPLACE TABLE FACT.FACT_ORDER_FULFILLMENT (
    ORDER_FULFILLMENT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    -- Foreign Keys (Date keys for each milestone)
    ORDER_DATE_KEY INTEGER,
    PAYMENT_DATE_KEY INTEGER,
    SHIP_DATE_KEY INTEGER,
    DELIVERY_DATE_KEY INTEGER,
    CUSTOMER_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER,
    -- Degenerate Dimensions
    ORDER_ID VARCHAR(100) NOT NULL,
    -- Measures
    QUANTITY INTEGER,
    ORDER_AMOUNT DECIMAL(12, 2),
    -- Lag measures (business days between milestones)
    ORDER_TO_PAYMENT_LAG INTEGER,
    PAYMENT_TO_SHIP_LAG INTEGER,
    SHIP_TO_DELIVERY_LAG INTEGER,
    ORDER_TO_DELIVERY_LAG INTEGER,
    -- Status flags
    IS_PAID BOOLEAN DEFAULT FALSE,
    IS_SHIPPED BOOLEAN DEFAULT FALSE,
    IS_DELIVERED BOOLEAN DEFAULT FALSE,
    IS_CANCELLED BOOLEAN DEFAULT FALSE,
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORDER_DATE_KEY, CUSTOMER_KEY)
COMMENT = 'Order fulfillment accumulating snapshot fact table';

-- ============================================
-- AGGREGATE FACT TABLES
-- ============================================

-- Daily Sales Aggregate
CREATE OR REPLACE TABLE FACT.FACT_DAILY_SALES_AGG (
    DATE_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    -- Aggregated Measures
    TOTAL_QUANTITY INTEGER,
    TOTAL_TRANSACTIONS INTEGER,
    TOTAL_GROSS_SALES DECIMAL(12, 2),
    TOTAL_DISCOUNT DECIMAL(12, 2),
    TOTAL_NET_SALES DECIMAL(12, 2),
    TOTAL_TAX DECIMAL(12, 2),
    TOTAL_AMOUNT DECIMAL(12, 2),
    TOTAL_PROFIT DECIMAL(12, 2),
    AVERAGE_TRANSACTION_VALUE DECIMAL(12, 2),
    -- Metadata
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DATE_KEY, STORE_KEY, PRODUCT_KEY),
    CONSTRAINT FK_AGG_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM.DIM_DATE(DATE_KEY),
    CONSTRAINT FK_AGG_STORE FOREIGN KEY (STORE_KEY) REFERENCES DIM.DIM_STORE(STORE_KEY),
    CONSTRAINT FK_AGG_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM.DIM_PRODUCT(PRODUCT_KEY)
)
CLUSTER BY (DATE_KEY, STORE_KEY)
COMMENT = 'Aggregated daily sales by store and product';

-- ============================================
-- VIEWS FOR EASY QUERYING
-- ============================================

-- Current Customer View (only current records)
CREATE OR REPLACE VIEW DIM.VW_CURRENT_CUSTOMERS AS
SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL,
    PHONE,
    CUSTOMER_SEGMENT,
    CUSTOMER_TIER,
    COUNTRY,
    STATE,
    CITY,
    POSTAL_CODE
FROM DIM.DIM_CUSTOMER
WHERE IS_CURRENT = TRUE;

-- Current Product View (only current records)
CREATE OR REPLACE VIEW DIM.VW_CURRENT_PRODUCTS AS
SELECT
    PRODUCT_KEY,
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_DESCRIPTION,
    SKU,
    BRAND,
    CATEGORY,
    SUBCATEGORY,
    DEPARTMENT,
    UNIT_COST,
    UNIT_PRICE,
    IS_ACTIVE
FROM DIM.DIM_PRODUCT
WHERE IS_CURRENT = TRUE;

-- Sales Summary View
CREATE OR REPLACE VIEW FACT.VW_SALES_SUMMARY AS
SELECT
    d.DATE_VALUE,
    d.YEAR,
    d.QUARTER,
    d.MONTH_NAME,
    c.CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    s.STORE_NAME,
    s.REGION,
    f.TRANSACTION_ID,
    f.QUANTITY,
    f.UNIT_PRICE,
    f.GROSS_SALES_AMOUNT,
    f.DISCOUNT_AMOUNT,
    f.NET_SALES_AMOUNT,
    f.TAX_AMOUNT,
    f.TOTAL_AMOUNT,
    f.PROFIT_AMOUNT
FROM FACT.FACT_SALES f
JOIN DIM.DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM.DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM.DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM.DIM_STORE s ON f.STORE_KEY = s.STORE_KEY;

-- ============================================
-- COMMENTS AND DOCUMENTATION
-- ============================================

COMMENT ON DATABASE RETAIL_DW IS 'Retail data warehouse following Kimball dimensional modeling methodology';
COMMENT ON SCHEMA DIM IS 'Dimension tables - descriptive attributes for analysis';
COMMENT ON SCHEMA FACT IS 'Fact tables - measurements and metrics';
COMMENT ON SCHEMA STAGING IS 'Staging area for ETL processing';
