"""
Edge Analytics for Industrial IoT

This module provides real-time analytics capabilities for edge computing:
- Anomaly detection algorithms
- Real-time aggregation and filtering
- Statistical analysis
- Predictive maintenance scoring
- Alert generation with smart deduplication
- Edge-based machine learning inference
"""

import numpy as np
from collections import deque
from typing import Dict, List, Tuple, Optional, Callable, Any
from dataclasses import dataclass
from datetime import datetime, timedelta
import logging
import json

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class AnalyticsConfig:
    """Configuration for edge analytics"""
    window_size: int = 100  # Size of rolling window
    threshold_std: float = 3.0  # Standard deviation threshold for anomalies
    min_history: int = 20  # Minimum values before anomaly detection
    alert_cooldown: float = 300  # Seconds between same alerts
    enable_forecasting: bool = True


@dataclass
class Alert:
    """Alert generated by analytics"""
    timestamp: datetime
    device_id: str
    metric_name: str
    alert_type: str  # "anomaly", "threshold", "trend"
    severity: str  # "low", "medium", "high", "critical"
    message: str
    value: float
    threshold: Optional[float] = None
    context: Optional[Dict[str, Any]] = None


class RollingWindowAnalytics:
    """Real-time aggregation using rolling windows"""

    def __init__(self, window_size: int = 100):
        self.window_size = window_size
        self.windows: Dict[str, deque] = {}

    def add_value(self, metric_name: str, value: float) -> Dict[str, float]:
        """Add value and return current statistics"""
        if metric_name not in self.windows:
            self.windows[metric_name] = deque(maxlen=self.window_size)

        self.windows[metric_name].append(value)

        if len(self.windows[metric_name]) < 2:
            return {"count": 1}

        values = list(self.windows[metric_name])
        return {
            "count": len(values),
            "mean": float(np.mean(values)),
            "std": float(np.std(values)),
            "min": float(np.min(values)),
            "max": float(np.max(values)),
            "median": float(np.median(values)),
            "p95": float(np.percentile(values, 95)),
            "p99": float(np.percentile(values, 99))
        }

    def get_statistics(self, metric_name: str) -> Optional[Dict[str, float]]:
        """Get current statistics for metric"""
        if metric_name not in self.windows or len(self.windows[metric_name]) == 0:
            return None

        values = list(self.windows[metric_name])
        return {
            "count": len(values),
            "mean": float(np.mean(values)),
            "std": float(np.std(values)),
            "min": float(np.min(values)),
            "max": float(np.max(values))
        }

    def get_recent_values(
        self,
        metric_name: str,
        count: int = 10
    ) -> List[float]:
        """Get recent values for metric"""
        if metric_name not in self.windows:
            return []
        values = list(self.windows[metric_name])
        return values[-count:]


class AnomalyDetector:
    """Detect anomalies using statistical methods"""

    def __init__(self, config: AnalyticsConfig = None):
        self.config = config or AnalyticsConfig()
        self.rolling_stats = RollingWindowAnalytics(self.config.window_size)
        self.anomaly_history: Dict[str, List[Tuple[datetime, float]]] = {}

    def is_anomaly(
        self,
        metric_name: str,
        value: float
    ) -> Tuple[bool, Optional[float]]:
        """
        Detect if value is anomalous

        Returns:
            (is_anomaly, z_score)
        """
        self.rolling_stats.add_value(metric_name, value)

        if metric_name not in self.anomaly_history:
            self.anomaly_history[metric_name] = deque(maxlen=1000)

        # Need baseline values
        if len(self.anomaly_history[metric_name]) < self.config.min_history:
            self.anomaly_history[metric_name].append((datetime.now(), value))
            return False, None

        stats = self.rolling_stats.get_statistics(metric_name)
        if stats is None:
            return False, None

        mean = stats["mean"]
        std = stats["std"]

        # Avoid division by zero
        if std < 1e-6:
            return False, None

        z_score = abs(value - mean) / std

        is_anomaly = z_score > self.config.threshold_std

        self.anomaly_history[metric_name].append((datetime.now(), value))

        return is_anomaly, z_score

    def get_anomaly_rate(self, metric_name: str) -> Optional[float]:
        """Get percentage of anomalies in history"""
        if metric_name not in self.anomaly_history:
            return None

        history = self.anomaly_history[metric_name]
        if len(history) == 0:
            return None

        # Check recent 100 values
        recent = list(history)[-100:]
        anomaly_count = 0

        for _, value in recent:
            is_anomaly, _ = self.is_anomaly(metric_name, value)
            if is_anomaly:
                anomaly_count += 1

        return (anomaly_count / len(recent)) * 100


class ThresholdAnalyzer:
    """Monitor metrics against static thresholds"""

    def __init__(self):
        self.thresholds: Dict[str, Dict[str, float]] = {}

    def set_threshold(
        self,
        metric_name: str,
        lower: Optional[float] = None,
        upper: Optional[float] = None
    ) -> None:
        """Set threshold bounds"""
        self.thresholds[metric_name] = {
            "lower": lower,
            "upper": upper
        }

    def check_threshold(
        self,
        metric_name: str,
        value: float
    ) -> Tuple[bool, Optional[str]]:
        """
        Check if value exceeds threshold

        Returns:
            (exceeds_threshold, violation_type)
        """
        if metric_name not in self.thresholds:
            return False, None

        threshold = self.thresholds[metric_name]

        if threshold["upper"] and value > threshold["upper"]:
            return True, f"above_upper_{threshold['upper']}"

        if threshold["lower"] and value < threshold["lower"]:
            return True, f"below_lower_{threshold['lower']}"

        return False, None


class TrendAnalyzer:
    """Detect trends in time series data"""

    def __init__(self, window_size: int = 50):
        self.window_size = window_size
        self.trends: Dict[str, deque] = {}

    def add_value(self, metric_name: str, value: float) -> Optional[str]:
        """
        Add value and detect trend

        Returns:
            Trend direction: "increasing", "decreasing", "stable", None
        """
        if metric_name not in self.trends:
            self.trends[metric_name] = deque(maxlen=self.window_size)

        self.trends[metric_name].append(value)

        if len(self.trends[metric_name]) < 10:
            return None

        values = list(self.trends[metric_name])

        # Linear regression slope
        x = np.arange(len(values))
        slope = np.polyfit(x, values, 1)[0]

        # Threshold for significant trend
        std = np.std(values)
        threshold = std * 0.1

        if slope > threshold:
            return "increasing"
        elif slope < -threshold:
            return "decreasing"
        else:
            return "stable"

    def get_trend_strength(self, metric_name: str) -> Optional[float]:
        """Get strength of current trend (0-1)"""
        if metric_name not in self.trends:
            return None

        values = list(self.trends[metric_name])
        if len(values) < 10:
            return None

        # Calculate R-squared of linear fit
        x = np.arange(len(values))
        z = np.polyfit(x, values, 1)
        p = np.poly1d(z)
        y_pred = p(x)

        ss_res = np.sum((values - y_pred) ** 2)
        ss_tot = np.sum((np.array(values) - np.mean(values)) ** 2)

        return float(1 - (ss_res / (ss_tot + 1e-6)))


class AlertingEngine:
    """Generate and manage alerts with deduplication"""

    def __init__(self, config: AnalyticsConfig = None):
        self.config = config or AnalyticsConfig()
        self.alerts: Dict[str, Alert] = {}
        self.alert_history: Dict[str, datetime] = {}
        self.alert_callbacks: List[Callable[[Alert], None]] = []

    def register_callback(self, callback: Callable[[Alert], None]) -> None:
        """Register callback for new alerts"""
        self.alert_callbacks.append(callback)

    def create_alert(
        self,
        device_id: str,
        metric_name: str,
        alert_type: str,
        severity: str,
        message: str,
        value: float,
        threshold: Optional[float] = None,
        context: Optional[Dict[str, Any]] = None
    ) -> Optional[Alert]:
        """
        Create alert with deduplication

        Returns:
            Alert if created, None if deduplicated
        """
        alert_key = f"{device_id}/{metric_name}/{alert_type}"

        # Check cooldown
        if alert_key in self.alert_history:
            time_since_alert = (
                datetime.now() - self.alert_history[alert_key]
            ).total_seconds()
            if time_since_alert < self.config.alert_cooldown:
                return None  # Still in cooldown

        # Create alert
        alert = Alert(
            timestamp=datetime.now(),
            device_id=device_id,
            metric_name=metric_name,
            alert_type=alert_type,
            severity=severity,
            message=message,
            value=value,
            threshold=threshold,
            context=context
        )

        # Update history
        self.alert_history[alert_key] = datetime.now()
        self.alerts[alert_key] = alert

        # Call callbacks
        for callback in self.alert_callbacks:
            try:
                callback(alert)
            except Exception as e:
                logger.error(f"Error in alert callback: {e}")

        return alert

    def get_active_alerts(self) -> List[Alert]:
        """Get all active alerts"""
        return list(self.alerts.values())

    def get_alert_summary(self) -> Dict[str, int]:
        """Get alert counts by severity"""
        summary = {"low": 0, "medium": 0, "high": 0, "critical": 0}
        for alert in self.alerts.values():
            summary[alert.severity] += 1
        return summary


class EdgeMLInference:
    """Run machine learning models at edge"""

    def __init__(self, model_type: str = "sklearn"):
        self.model_type = model_type
        self.model = None
        self.scaler = None
        self.feature_names: List[str] = []

    def load_model(self, model_path: str) -> bool:
        """Load pre-trained model"""
        try:
            if self.model_type == "sklearn":
                import pickle
                with open(model_path, 'rb') as f:
                    self.model = pickle.load(f)
                logger.info(f"Loaded sklearn model from {model_path}")
                return True

            elif self.model_type == "tflite":
                try:
                    from tensorflow.lite.python import interpreter
                    self.model = interpreter.Interpreter(model_path=model_path)
                    self.model.allocate_tensors()
                    logger.info(f"Loaded TFLite model from {model_path}")
                    return True
                except ImportError:
                    logger.error("TensorFlow not available")
                    return False

        except Exception as e:
            logger.error(f"Error loading model: {e}")
            return False

    def predict(self, features: Dict[str, float]) -> Optional[float]:
        """Run inference on features"""
        if self.model is None:
            logger.warning("Model not loaded")
            return None

        try:
            # Extract features in correct order
            feature_values = [
                features[name] for name in self.feature_names
            ]

            if self.model_type == "sklearn":
                prediction = self.model.predict([feature_values])[0]
                return float(prediction)

            elif self.model_type == "tflite":
                input_details = self.model.get_input_details()
                output_details = self.model.get_output_details()

                input_index = input_details[0]['index']
                self.model.set_tensor(
                    input_index,
                    np.array([feature_values], dtype=np.float32)
                )

                self.model.invoke()

                output_index = output_details[0]['index']
                output = self.model.get_tensor(output_index)

                return float(output[0][0])

        except Exception as e:
            logger.error(f"Error during inference: {e}")
            return None

    def predict_failure_probability(
        self,
        equipment_id: str,
        metrics: Dict[str, float]
    ) -> Optional[Dict[str, Any]]:
        """Predict equipment failure probability"""
        prediction = self.predict(metrics)

        if prediction is None:
            return None

        # Interpret probability
        failure_prob = max(0, min(1, prediction))

        if failure_prob > 0.7:
            severity = "critical"
            action = "schedule_immediate_maintenance"
            rul_days = max(1, int((1 - failure_prob) * 10))

        elif failure_prob > 0.4:
            severity = "warning"
            action = "increase_monitoring"
            rul_days = max(1, int((1 - failure_prob) * 30))

        else:
            severity = "normal"
            action = "continue_normal_operation"
            rul_days = None

        return {
            "failure_probability": failure_prob,
            "severity": severity,
            "recommended_action": action,
            "estimated_remaining_days": rul_days,
            "prediction_timestamp": datetime.now().isoformat()
        }


class ComprehensiveEdgeAnalytics:
    """Integrated edge analytics engine"""

    def __init__(self, config: AnalyticsConfig = None):
        self.config = config or AnalyticsConfig()
        self.anomaly_detector = AnomalyDetector(self.config)
        self.threshold_analyzer = ThresholdAnalyzer()
        self.trend_analyzer = TrendAnalyzer()
        self.alerting_engine = AlertingEngine(self.config)
        self.ml_inference = EdgeMLInference()

    def process_metric(
        self,
        device_id: str,
        metric_name: str,
        value: float
    ) -> List[Alert]:
        """Process metric and generate alerts"""
        alerts = []

        # 1. Anomaly detection
        is_anomaly, z_score = self.anomaly_detector.is_anomaly(metric_name, value)
        if is_anomaly:
            alert = self.alerting_engine.create_alert(
                device_id=device_id,
                metric_name=metric_name,
                alert_type="anomaly",
                severity="high",
                message=f"{metric_name} is anomalous (z-score: {z_score:.2f})",
                value=value,
                context={"z_score": z_score}
            )
            if alert:
                alerts.append(alert)

        # 2. Threshold checking
        exceeds, violation = self.threshold_analyzer.check_threshold(
            metric_name,
            value
        )
        if exceeds:
            alert = self.alerting_engine.create_alert(
                device_id=device_id,
                metric_name=metric_name,
                alert_type="threshold",
                severity="high",
                message=f"{metric_name} threshold violated: {violation}",
                value=value,
                context={"violation": violation}
            )
            if alert:
                alerts.append(alert)

        # 3. Trend analysis
        trend = self.trend_analyzer.add_value(metric_name, value)
        if trend == "increasing":
            strength = self.trend_analyzer.get_trend_strength(metric_name)
            if strength and strength > 0.8:
                alert = self.alerting_engine.create_alert(
                    device_id=device_id,
                    metric_name=metric_name,
                    alert_type="trend",
                    severity="medium",
                    message=f"{metric_name} showing strong increasing trend",
                    value=value,
                    context={"trend": trend, "strength": strength}
                )
                if alert:
                    alerts.append(alert)

        return alerts

    def get_health_score(self, device_id: str) -> float:
        """Calculate device health score (0-100)"""
        alerts = self.alerting_engine.get_active_alerts()
        device_alerts = [a for a in alerts if a.device_id == device_id]

        if not device_alerts:
            return 100.0

        severity_weights = {"low": 5, "medium": 15, "high": 30, "critical": 50}
        total_penalty = sum(
            severity_weights.get(a.severity, 0) for a in device_alerts
        )

        health_score = max(0, 100 - total_penalty)
        return float(health_score)

    def get_device_status_report(self, device_id: str) -> Dict[str, Any]:
        """Generate comprehensive device status report"""
        alerts = self.alerting_engine.get_active_alerts()
        device_alerts = [a for a in alerts if a.device_id == device_id]

        return {
            "device_id": device_id,
            "timestamp": datetime.now().isoformat(),
            "health_score": self.get_health_score(device_id),
            "active_alerts": len(device_alerts),
            "alert_summary": self.alerting_engine.get_alert_summary(),
            "top_alerts": [
                {
                    "metric": a.metric_name,
                    "severity": a.severity,
                    "message": a.message
                }
                for a in sorted(
                    device_alerts,
                    key=lambda x: {"critical": 0, "high": 1, "medium": 2, "low": 3}[x.severity]
                )[:5]
            ]
        }


# Example usage
if __name__ == "__main__":
    # Initialize analytics
    analytics = ComprehensiveEdgeAnalytics()

    # Set thresholds
    analytics.threshold_analyzer.set_threshold("temperature", lower=0, upper=100)
    analytics.threshold_analyzer.set_threshold("vibration", lower=0, upper=5)

    # Register alert callback
    def on_alert(alert: Alert):
        logger.warning(
            f"ALERT: {alert.device_id}/{alert.metric_name} - {alert.message}"
        )

    analytics.alerting_engine.register_callback(on_alert)

    # Simulate processing metrics
    import random
    device_id = "motor-01"

    for i in range(100):
        temperature = random.gauss(45, 5)  # Mean 45, std 5
        vibration = random.gauss(1.0, 0.3)  # Mean 1.0, std 0.3

        alerts = analytics.process_metric(device_id, "temperature", temperature)
        alerts.extend(analytics.process_metric(device_id, "vibration", vibration))

        if alerts:
            for alert in alerts:
                print(f"Alert: {alert.message}")

    # Get device status
    status = analytics.get_device_status_report(device_id)
    print(f"\nDevice Status: {json.dumps(status, indent=2)}")
