-- PARTITIONING EXAMPLE (PostgreSQL)
CREATE TABLE FACT_SALES_PARTITIONED (
    sales_key BIGSERIAL,
    date_key INTEGER NOT NULL,
    amount DECIMAL(12,2)
) PARTITION BY RANGE (date_key);

CREATE TABLE fact_sales_2024_01 PARTITION OF FACT_SALES_PARTITIONED
    FOR VALUES FROM (20240101) TO (20240201);
